[build]
publish = "src/"

[[redirects]]
from = "https://arnaud.sh/leaks/leak-admis-42lyon-2021-08.txt"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
force = true

[[redirects]]
from = "http://arnaud.sh/leaks/leak-admis-42lyon-2021-08.txt"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
force = true
